### ISSUE TITLE
Eliminar símbolos inúteis e inférteis

### ISSUE THREAD

**Issue by DouglasFuelber** [DouglasFuelber/free-context-grammar-manipulator#5]
- [x] Eliminar símbolos ínuteis
- [x] Eliminar símbolos inférteis

**Comment by felipehertzer** [comment]
A principio é isso temos que testar

**Comment by DouglasFuelber** [comment]
Só realizei a ordenção das chamadas das funções neste [último commit](https://github.com/DouglasFuelber/free-context-grammar-manipulator/commit/e23b56298fba73da6364a6687e869ee18bbb5e21) e está dando um erro dentro de um each. Tá pegando um undefined.

**Comment by DouglasFuelber** [comment]
Ainda precisa verifica aquele caso do E e F que passei
