### ISSUE TITLE
Eliminar recursão à esquerda

### ISSUE THREAD

**Issue by DouglasFuelber** [DouglasFuelber/free-context-grammar-manipulator#7]

**Comment by felipehertzer** [comment]
Feito, assim toda fez que ele encontra o mesmo nao terminal no complemento como por exemplo
E -> Ee | e ele remove elemento e o primeiro char adiciona o E' no final = eE' do que sobrou e cria um novo elemento no info.clones E' com elemento removido e também adicionei para que haja suporte para multi recursões na mesma linha

**Comment by DouglasFuelber** [comment]
Vou testar ainda
